### ISSUE TITLE
Wie lang bruchts ca.

### ISSUE THREAD

**Issue by EuropeanVirtual** [RoadJDK/EnergyAir-Bot-2021#1]
Wie lang bruchts  System ums Gwünne

**Comment by RoadJDK** [comment]
Kommt ganz auf die Vergabe von Energy drauf an. Für die meisten hat es zwischen 2.5h - 4 gedauert. Am besten benutzt du das Programm am Morgen-Mittag, da sind die meisten Tickets noch nicht vergeben.

**Comment by EuropeanVirtual** [comment]
Ah Easy,  hat Funktioniert
