### ISSUE TITLE
Energy air bot 21

### ISSUE THREAD

**Issue by briann1992** [RoadJDK/EnergyAir-Bot-2021#3]
hello i have just downloaded your script, why is it not automatically selected the symbols or did i do something wrong?

Can you answer me on email : n_ga92@hotmail.com

**Comment by RoadJDK** [comment]
Did you follow my instructions on the readme file?

**Comment by briann1992** [comment]
Yes but i found an another bot in the github site lg brian

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________
